import { test, expect } from '@playwright/test';

test('client basic test', async ({ page }) => {
  await page.goto('http://localhost:3000/');
  await page.getByText('Featured ServicesView allDentistBook an experienced dental specialist to').click();
  await page.getByRole('link', { name: 'Sign In' }).click();
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.getByRole('button', { name: 'Login' }).click();
  await page.getByText('Login Failed').click();
  await page.getByRole('listitem').click();
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.getByRole('textbox', { name: 'Email' }).fill('qwer');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('button', { name: 'Login' }).click();
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.getByRole('textbox', { name: 'Email' }).fill('gayashankdd@gmail.com');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('123');
  await page.locator('div').filter({ hasText: /^Password$/ }).getByRole('button').click();
  await page.locator('div').filter({ hasText: /^Password$/ }).getByRole('button').click();
  await page.getByRole('button', { name: 'Login' }).click();
  
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('12345678');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.getByText('logoHomeServicesDGd gayashan').click();
  await page.getByRole('button', { name: 'DG d gayashan' }).click();
  await page.locator('html').click();
  await page.getByRole('button', { name: 'DG d gayashan' }).click();
  await page.getByRole('menuitem', { name: 'Profile' }).click();
  await page.getByRole('button', { name: 'DG d gayashan' }).click();
  await page.locator('html').click();
  await page.getByText('d gayashangayashankdd@gmail.').click();
  await page.getByRole('heading', { name: 'd gayashan' }).click();
  await page.getByRole('button', { name: 'DG d gayashan' }).click();
  await page.locator('html').click();
  await page.getByRole('navigation').getByRole('link', { name: 'Services' }).click();
  await page.getByRole('button', { name: 'Browse Service Providers' }).first().click();
 
  await page.getByRole('navigation').getByRole('link', { name: 'Home' }).click();
  await page.goto('http://localhost:3000/');
  await page.getByText('Featured ServicesView allDentistBook an experienced dental specialist to').click();
  await page.reload();
  await page.getByRole('button', { name: 'Browse Service Providers' }).first().click();
  await page.getByRole('button', { name: 'Book Now' }).first().click();
  await page.getByRole('gridcell', { name: '6', exact: true }).click();
  await page.getByRole('button', { name: '14:00' }).click();
  await page.getByRole('button', { name: 'Confirm Appointment' }).click();
  await page.getByRole('button', { name: 'Book Without Note' }).click();
  await page.getByRole('navigation').getByRole('link', { name: 'Home' }).click();
  await page.getByText('NSDentistNaveen Samarawickrama2025-06-0613:00:00 - 13:15:00UpcomingCancel').click();
  await page.getByRole('button', { name: 'DG d gayashan' }).click();
  await page.getByRole('menuitem', { name: 'Logout' }).click();
});