import { test, expect } from '@playwright/test';

test('service provider login', async ({ page }) => {
  await page.goto('http://localhost:3000/');
  await expect(page.getByRole('link', { name: 'Sign In' })).toBeVisible();
  await page.getByRole('link', { name: 'Sign In' }).click();
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.getByRole('textbox', { name: 'Email' }).fill('gayashandile@gmail.com');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('12345678');
  await expect(page.locator('div').filter({ hasText: /^Password$/ }).getByRole('button')).toBeVisible();
  await page.locator('div').filter({ hasText: /^Password$/ }).getByRole('button').click();
  await expect(page.getByRole('textbox', { name: 'Password' })).toBeVisible();
  await expect(page.locator('div').filter({ hasText: /^Password$/ }).getByRole('button')).toBeVisible();
  await page.locator('div').filter({ hasText: /^Password$/ }).getByRole('button').click();
  await expect(page.getByRole('textbox', { name: 'Password' })).toBeVisible();
  await page.getByRole('button', { name: 'Login' }).click();
  await expect(page.getByText('Login Failed')).toBeVisible();
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('123123123');
  await page.getByRole('button', { name: 'Login' }).click();
  await expect(page.getByText('Login Successful')).toBeVisible();
  await expect(page.getByText('Logged in as a service')).toBeVisible();
  await page.goto('http://localhost:3000/serviceproviderdashboard');
  await expect(page.getByRole('heading', { name: 'Service Provider Dashboard' })).toBeVisible();
  await expect(page.getByText('Friday, June 6,')).toBeVisible();
  await expect(page.getByText('Daily Schedule08:')).toBeVisible();
  await expect(page.getByText('Schedule for June 3, 2025Appointments today: 0Block TimeNo appointments')).toBeVisible();
  await expect(page.getByRole('button', { name: 'Block Time' })).toBeVisible();
  await expect(page.getByText('Appointment Management')).toBeVisible();
  await page.getByRole('tab', { name: 'Upcoming' }).click();
  await page.getByRole('tab', { name: 'Past' }).click();
  await page.getByRole('tab', { name: 'Today' }).click();
  await expect(page.getByRole('button').first()).toBeVisible();
  await page.getByRole('button').first().click();
  await expect(page.getByRole('menuitem', { name: 'Profile' })).toBeVisible();
  await expect(page.getByRole('menuitem', { name: 'Logout' })).toBeVisible();
  await page.getByText('Logout').click();
});