import { test, expect } from '@playwright/test';

test('client sign up', async ({ page }) => {
  await page.goto('http://localhost:3000/');
  await page.getByRole('link', { name: 'Sign In' }).click();
  await page.getByRole('link', { name: 'Sign up' }).click();
  await page.getByRole('button', { name: 'Client Account Looking for' }).click();
  await page.getByText('Create your client account to').first().click();

  await page.getByRole('textbox', { name: 'Last Name *' }).click();
  await page.getByRole('textbox', { name: 'Contact Number' }).click();
  await page.getByRole('textbox', { name: 'First Name *' }).click();
  await page.getByRole('textbox', { name: 'Email *' }).click();
  await page.getByRole('spinbutton', { name: 'Age *' }).click();
  await page.getByRole('textbox', { name: 'First Name *' }).click();
  await page.getByRole('textbox', { name: 'First Name *' }).fill('S');
  await page.getByRole('textbox', { name: 'Last Name *' }).click();
  await page.getByRole('textbox', { name: 'Last Name *' }).fill('shadow');
  await page.getByRole('textbox', { name: 'Email *' }).click();
  await page.getByRole('textbox', { name: 'Email *' }).fill('ashborn541@gmail.com');
  await page.getByRole('textbox', { name: 'Contact Number' }).click();
  await page.getByRole('textbox', { name: 'Email *' }).click();
  await page.getByRole('textbox', { name: 'Email *' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Email *' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Email *' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Email *' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Email *' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Email *' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Email *' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Email *' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Email *' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Email *' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Email *' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Contact Number' }).click();
  await page.getByRole('textbox', { name: 'Contact Number' }).fill('0456123789');
  await page.getByRole('spinbutton', { name: 'Age *' }).click();
  await page.getByRole('spinbutton', { name: 'Age *' }).fill('25');
  await page.getByRole('radio', { name: 'Male', exact: true }).click();
  await page.getByRole('textbox', { name: 'Address' }).click();
  await page.getByRole('textbox', { name: 'Address' }).fill('horana');
  await page.getByRole('textbox', { name: 'Password *', exact: true }).click();
  await page.getByRole('textbox', { name: 'Password *', exact: true }).fill('12');
  await page.getByRole('textbox', { name: 'Password *', exact: true }).click();
  await page.getByRole('textbox', { name: 'Password *', exact: true }).fill('12345678');
  await page.getByRole('textbox', { name: 'Confirm Password *' }).click();
  await page.getByRole('textbox', { name: 'Confirm Password *' }).fill('12');
  await page.getByRole('textbox', { name: 'Confirm Password *' }).click();
  await page.getByRole('textbox', { name: 'Confirm Password *' }).fill('12345678');
  await page.locator('div').filter({ hasText: /^Confirm Password \*Passwords match$/ }).getByRole('button').click();
  await page.locator('div').filter({ hasText: /^Confirm Password \*Passwords match$/ }).getByRole('button').click();
  await page.locator('div').filter({ hasText: /^Password \*Weak passwordUse uppercase, lowercase, numbers, and special characters$/ }).getByRole('button').click();
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.locator('div').filter({ hasText: /^I'm not a robot$/ }).click();
  await page.getByRole('checkbox', { name: 'I\'m not a robot' }).click();
  await page.getByRole('button', { name: 'Send Verification Code' }).click();

  // Pause for manual OTP input
  console.log('\n🔍 Please check your email for the verification code.');
  console.log('Enter the code in the browser window and press "Enter" to continue.\n');
  await page.pause();

  await page.getByRole('button', { name: 'Verify Code' }).click();
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.getByRole('combobox').first().selectOption('1');
  await page.getByRole('textbox', { name: 'Your answer' }).first().click();
  await page.getByRole('textbox', { name: 'Your answer' }).first().fill('cat');
  await page.getByRole('combobox').nth(1).selectOption('2');
  await page.getByRole('textbox', { name: 'Your answer' }).nth(1).click();
  await page.getByRole('textbox', { name: 'Your answer' }).nth(1).fill('mom');
  await page.getByRole('combobox').nth(2).selectOption('8');
  await page.getByRole('textbox', { name: 'Your answer' }).nth(2).click();
  await page.getByRole('textbox', { name: 'Your answer' }).nth(2).fill('pop');
  await page.getByRole('button', { name: 'Create Client Account' }).click();
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.getByRole('textbox', { name: 'Email' }).fill('ashborn541@gmail.com');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('12345678');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.getByRole('button', { name: 'S shadow' }).click();
  await page.getByRole('menuitem', { name: 'Logout' }).click();
});