import { test, expect } from '@playwright/test';

test('client sign up', async ({ page }) => {
  await page.goto('http://localhost:3000/');
  await expect(page.getByRole('link', { name: 'Sign In' })).toBeVisible();
  await page.getByRole('link', { name: 'Sign In' }).click();
  await expect(page.getByText('logoWelcome back! Please login to your account.EmailPasswordRemember meForgot')).toBeVisible();
  await expect(page.getByText('Don\'t have an account? Sign up')).toBeVisible();
  await expect(page.getByRole('link', { name: 'Sign up' })).toBeVisible();
  await page.getByRole('link', { name: 'Sign up' }).click();
  await expect(page.locator('div').filter({ hasText: /^Registration ProcessChoose your account type to get started$/ }).locator('div')).toBeVisible();
  await expect(page.getByText('Choose your account type to')).toBeVisible();
  await page.getByRole('button', { name: 'Client Account Looking for' }).click();
  await expect(page.getByRole('link', { name: 'Back to Account Selection' })).toBeVisible();
  await expect(page.getByText('Client Registration')).toBeVisible();
  await page.getByText('Create your client account to').first().click();
  await expect(page.locator('div').filter({ hasText: /^Personal Info$/ }).locator('div').first()).toBeVisible();
  await expect(page.getByText('Personal Info', { exact: true })).toBeVisible();
  await expect(page.getByRole('heading', { name: 'Personal Information' })).toBeVisible();
  await expect(page.getByText('Profile Image')).toBeVisible();
  await expect(page.locator('div').filter({ hasText: /^Profile ImageMaximum file size: 5MB\. Recommended dimensions: 200x200px\.$/ }).locator('div').first()).toBeVisible();
 



  await page.getByRole('textbox', { name: 'Last Name *' }).click();
  await page.getByRole('textbox', { name: 'Contact Number' }).click();
  await page.getByRole('textbox', { name: 'First Name *' }).click();
  await page.getByRole('textbox', { name: 'Email *' }).click();
   await page.getByRole('spinbutton', { name: 'Age *' }).click();
  await expect(page.getByText('First name is required')).toBeVisible();
  await expect(page.getByText('Last name is required')).toBeVisible();
  await expect(page.getByText('Email is required')).toBeVisible();
  await page.getByRole('textbox', { name: 'First Name *' }).click();
  await page.getByRole('textbox', { name: 'First Name *' }).fill('S');
  await page.getByRole('textbox', { name: 'Last Name *' }).click();
  await page.getByRole('textbox', { name: 'Last Name *' }).fill('shadow');
  await page.getByRole('textbox', { name: 'Email *' }).click();
  await page.getByRole('textbox', { name: 'Email *' }).fill('ashborn541@gmail.com');
  await page.getByRole('textbox', { name: 'Contact Number' }).click();
  await page.getByRole('textbox', { name: 'Email *' }).click();
  await page.getByRole('textbox', { name: 'Email *' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Email *' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Email *' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Email *' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Email *' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Email *' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Email *' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Email *' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Email *' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Email *' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Email *' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Contact Number' }).click();
  await page.getByRole('textbox', { name: 'Contact Number' }).fill('0456123789');
  await page.getByRole('spinbutton', { name: 'Age *' }).click();
  await page.getByRole('spinbutton', { name: 'Age *' }).fill('25');
  await page.getByRole('radio', { name: 'Male', exact: true }).click();
  await page.getByRole('textbox', { name: 'Address' }).click();
  await page.getByRole('textbox', { name: 'Address' }).fill('horana');
  await page.getByRole('textbox', { name: 'Password *', exact: true }).click();
  await page.getByRole('textbox', { name: 'Password *', exact: true }).fill('12');
  await expect(page.getByRole('button').nth(1)).toBeVisible();
  await expect(page.getByText('Password must be at least 8')).toBeVisible();
  await expect(page.getByText('Use uppercase, lowercase,')).toBeVisible();
  await expect(page.getByText('Weak password')).toBeVisible();
  await page.getByRole('textbox', { name: 'Password *', exact: true }).click();
  await page.getByRole('textbox', { name: 'Password *', exact: true }).fill('12345678');
  await page.getByRole('textbox', { name: 'Confirm Password *' }).click();
  await page.getByRole('textbox', { name: 'Confirm Password *' }).fill('12');
  await expect(page.getByText('Passwords do not match')).toBeVisible();
  await page.getByRole('textbox', { name: 'Confirm Password *' }).click();
  await page.getByRole('textbox', { name: 'Confirm Password *' }).fill('12345678');
  await expect(page.getByText('Passwords match')).toBeVisible();
  await expect(page.locator('div').filter({ hasText: /^Confirm Password \*Passwords match$/ }).getByRole('button')).toBeVisible();
  await page.locator('div').filter({ hasText: /^Confirm Password \*Passwords match$/ }).getByRole('button').click();
  await expect(page.locator('div').filter({ hasText: /^Confirm Password \*Passwords match$/ }).getByRole('button')).toBeVisible();
  await page.locator('div').filter({ hasText: /^Confirm Password \*Passwords match$/ }).getByRole('button').click();
  await expect(page.locator('div').filter({ hasText: /^Password \*Weak passwordUse uppercase, lowercase, numbers, and special characters$/ }).getByRole('button')).toBeVisible();
  await page.locator('div').filter({ hasText: /^Password \*Weak passwordUse uppercase, lowercase, numbers, and special characters$/ }).getByRole('button').click();
  await expect(page.locator('div').filter({ hasText: /^Password \*Weak passwordUse uppercase, lowercase, numbers, and special characters$/ }).getByRole('button')).toBeVisible();
  await expect(page.getByRole('button', { name: 'Continue' })).toBeVisible();
  await page.getByRole('button', { name: 'Continue' }).click();
  await expect(page.getByRole('heading', { name: 'Human Verification' })).toBeVisible();
  await expect(page.getByRole('heading', { name: 'Email Verification' })).toBeVisible();
  await page.locator('div').filter({ hasText: /^I'm not a robot$/ }).click();
  await page.getByRole('checkbox', { name: 'I\'m not a robot' }).click();
  await expect(page.getByText('You can now proceed to email')).toBeVisible();
  await expect(page.getByRole('button', { name: 'Send Verification Code' })).toBeVisible();
  await page.getByRole('button', { name: 'Send Verification Code' }).click();
  await expect(page.getByText('We\'ll send a 6-digit verification code to: ashborn541@gmail.comSending')).toBeVisible();
  await expect(page.getByText('OTP Sent')).toBeVisible();

  // Pause for manual OTP input
  console.log('\n🔍 Please check your email for the verification code.');
  console.log('Enter the code in the browser window and press "Enter" to continue.\n');
  await page.pause();

  await page.getByRole('button', { name: 'Verify Code' }).click();
  await expect(page.getByText('Success', { exact: true })).toBeVisible();
  await expect(page.getByText('Email verified successfully,')).toBeVisible();
  await expect(page.getByText('Email verified successfully!')).toBeVisible();
  await page.getByRole('button', { name: 'Continue' }).click();
  await expect(page.getByRole('heading', { name: 'Security Questions' })).toBeVisible();
  await page.getByRole('combobox').first().selectOption('1');
  await page.getByRole('textbox', { name: 'Your answer' }).first().click();
  await page.getByRole('textbox', { name: 'Your answer' }).first().fill('cat');
  await page.getByRole('combobox').nth(1).selectOption('2');
  await page.getByRole('textbox', { name: 'Your answer' }).nth(1).click();
  await page.getByRole('textbox', { name: 'Your answer' }).nth(1).fill('mom');
  await page.getByRole('combobox').nth(2).selectOption('8');
  await page.getByRole('textbox', { name: 'Your answer' }).nth(2).click();
  await page.getByRole('textbox', { name: 'Your answer' }).nth(2).fill('pop');
  await page.getByRole('button', { name: 'Create Client Account' }).click();
  await expect(page.getByText('Registration successful!')).toBeVisible();
  await expect(page.getByText('logo')).toBeVisible();
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.getByRole('textbox', { name: 'Email' }).fill('ashborn541@gmail.com');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('12345678');
  await page.getByRole('button', { name: 'Login' }).click();
 
  await expect(page.getByRole('heading', { name: 'Welcome back, d' })).toBeVisible();
  await page.getByRole('button', { name: 'd dilesh' }).click();
  await page.getByRole('menuitem', { name: 'Logout' }).click();
  await expect(page.getByRole('link', { name: 'Sign In' })).toBeVisible();
});