import { test, expect } from '@playwright/test';

test('forgot password', async ({ page }) => {
  await page.goto('http://localhost:3000/');
  await expect(page.getByRole('link', { name: 'Sign In' })).toBeVisible();
  await page.getByRole('link', { name: 'Sign In' }).click();
  
  await expect(page.getByRole('link', { name: 'Forgot Password?' })).toBeVisible();
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.getByRole('link', { name: 'Forgot Password?' }).click();
  await expect(page.getByText('Email Required')).toBeVisible();
  await expect(page.getByText('Please enter your email')).toBeVisible();
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.getByRole('textbox', { name: 'Email' }).fill('gayashankdd@gmail.com');
  await page.getByRole('link', { name: 'Forgot Password?' }).click();
  await expect(page.getByRole('heading', { name: 'Reset Password' })).toBeVisible();
  await expect(page.getByText('Select your account type to')).toBeVisible();
  await expect(page.getByRole('button', { name: 'Client' })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Service Provider' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Back to Login' })).toBeVisible();
  await page.getByRole('button', { name: 'Client' }).click();
  await expect(page.getByRole('heading', { name: 'Security Questions' })).toBeVisible();
  await expect(page.getByText('Please select and answer')).toBeVisible();
  await expect(page.getByText('Email: gayashankdd@gmail.com')).toBeVisible();
  await page.getByRole('combobox').first().selectOption('1');
  await page.getByRole('textbox', { name: 'Enter your answer' }).first().click();
  await page.getByRole('textbox', { name: 'Enter your answer' }).first().fill('cat');
  await page.getByRole('combobox').nth(1).selectOption('2');
  await page.getByRole('textbox', { name: 'Enter your answer' }).nth(1).click();
  await page.getByRole('textbox', { name: 'Enter your answer' }).nth(1).fill('mom');
  await page.getByRole('combobox').nth(2).selectOption('8');
  await page.getByRole('textbox', { name: 'Enter your answer' }).nth(2).click();
  await page.getByRole('textbox', { name: 'Enter your answer' }).nth(2).fill('popp');
  await page.getByRole('button', { name: 'Verify Security Questions' }).click();
  await expect(page.getByText('Verification Failed')).toBeVisible();
  await expect(page.getByText('The answers provided do not match our records. Please check your answers and')).toBeVisible();
  await page.getByRole('textbox', { name: 'Enter your answer' }).nth(2).click();
  await page.getByRole('textbox', { name: 'Enter your answer' }).nth(2).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Enter your answer' }).nth(2).fill('pop');
  await page.getByRole('button', { name: 'Verify Security Questions' }).click();
  await expect(page.getByText('Questions Verified', { exact: true })).toBeVisible();
  await expect(page.getByText('Security questions verified')).toBeVisible();
  await expect(page.getByRole('heading', { name: 'Create New Password' })).toBeVisible();
  await expect(page.getByText('Enter your new password')).toBeVisible();
  await expect(page.getByRole('textbox', { name: 'New Password', exact: true })).toBeVisible();
  await expect(page.getByRole('textbox', { name: 'Confirm New Password' })).toBeVisible();
  await page.getByRole('button', { name: 'Back' }).click();
  await page.getByRole('button', { name: 'Verify Security Questions' }).click();
  await page.getByRole('textbox', { name: 'New Password', exact: true }).click();
  await page.getByRole('textbox', { name: 'New Password', exact: true }).fill('12344');
  await expect(page.getByRole('button').filter({ hasText: /^$/ }).first()).toBeVisible();
  await page.getByRole('button').filter({ hasText: /^$/ }).first().click();
  await page.getByRole('textbox', { name: 'New Password', exact: true }).click();
  await page.getByRole('textbox', { name: 'New Password', exact: true }).fill('12345678');
  await expect(page.getByRole('button').filter({ hasText: /^$/ }).first()).toBeVisible();
  await page.getByRole('button').filter({ hasText: /^$/ }).first().click();
  await page.getByRole('textbox', { name: 'Confirm New Password' }).click();
  await page.getByRole('textbox', { name: 'Confirm New Password' }).fill('12345678');
  await page.getByRole('button', { name: 'Reset Password' }).click();
  await expect(page.getByText('Password Reset Successful', { exact: true })).toBeVisible();
  await expect(page.getByText('Your password has been reset')).toBeVisible();
  await expect(page.getByRole('heading', { name: 'Password Reset Successful!' })).toBeVisible();
  await expect(page.getByText('Password Reset Successful!Your password has been successfully reset. You can')).toBeVisible();
  await page.getByRole('button', { name: 'Back to Login' }).click();
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.getByRole('textbox', { name: 'Email' }).fill('gayashankdd@gmail.com');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('12345678');
  await expect(page.locator('div').filter({ hasText: /^Password$/ }).getByRole('button')).toBeVisible();
  await page.locator('div').filter({ hasText: /^Password$/ }).getByRole('button').click();
  await expect(page.locator('div').filter({ hasText: /^Password$/ }).getByRole('button')).toBeVisible();
  await page.locator('div').filter({ hasText: /^Password$/ }).getByRole('button').click();
  await page.getByRole('button', { name: 'Login' }).click();
  await expect(page.getByText('logoHomeServicesDDd dilesh')).toBeVisible();
  await page.getByRole('button', { name: 'DD d dilesh' }).click();
  await page.getByRole('menuitem', { name: 'Logout' }).click();
});